# Generated by Django 4.2.17 on 2025-01-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("functional_requirements", models.TextField()),
                ("non_functional_requirements", models.TextField()),
                ("data_requirements", models.TextField()),
                ("project_scope", models.TextField()),
                ("constraints", models.TextField()),
                ("existing_resources", models.TextField()),
                ("ui_ux_design", models.TextField(blank=True, null=True)),
                ("user_roles", models.TextField(blank=True, null=True)),
                ("mid_stage_feedback", models.TextField(blank=True, null=True)),
                ("test_cases", models.TextField(blank=True, null=True)),
                ("acceptance_criteria", models.TextField(blank=True, null=True)),
                ("data_samples", models.TextField(blank=True, null=True)),
                ("production_requirements", models.TextField(blank=True, null=True)),
                ("permission_settings", models.TextField(blank=True, null=True)),
                ("go_live_support", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
