# Generated by Django 4.2.17 on 2025-01-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_customerinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CopilotResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_data", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer_info",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copilot_response",
                        to="myapp.customerinfo",
                    ),
                ),
            ],
        ),
    ]
